### ISSUE TITLE
please consider merging with "github.com/cockroachdb/cmux"

### ISSUE THREAD

**Issue by onlyjob** [soheilhy/cmux#26]
[github.com/cockroachdb/cmux](https://github.com/cockroachdb/cmux) is a _cmus_ fork incorporated into Etcd v3. Needless forking is harmful. Perhaps both projects could join efforts and benefit from working together?

**Comment by soheilhy** [comment]
cockroachdb decided to maintain its own fork. So, it's really out of my control. I'm happy to merge pull-requests.
