### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by onlyjob** [soheilhy/cmux#27]
Please consider assigning version numbers and tagging releases. Tags/releases
are useful for downstream package maintainers (in [Debian](http://debian.org) and other distributions) to export source tarballs, automatically track new releases and to declare dependencies between packages. Read more in the [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

Versioning provides additional benefits to encourage vendoring of a particular (e.g. latest stable) release contrary to random unreleased snapshots.

Thank you.

See also

 * http://semver.org/
 * https://en.wikipedia.org/wiki/Software_versioning

**Comment by soheilhy** [comment]
We have v0.1.0 now. thanks.

**Comment by onlyjob** [comment]
Thank you. :)
