### ISSUE TITLE
How to serve gRPC + SSH with cmux?

### ISSUE THREAD

**Issue by arkan** [soheilhy/cmux#44]
Hi, 

I'm trying to use `cmux` to serve gRPC + SSH connections, but I cannot make it works. 

```go
lis, _ := net.Listen("tcp", ":8080")

l := cmux.New(lis)
grpcL := l.Match(cmux.HTTP2HeaderField("content-type", "application/grpc"))
sshL := l.Match(cmux.Any())
```
It serves gRPC well but it blocks when I connect with a ssh client. 

If I comment the gRPC `Match` the SSH connections work. Am I doing something wrong? 

Thanks

**Comment by soheilhy** [comment]
That's odd. I will have to take a look. Does your SSH connection send the
HTTP2  preface?

On Fri, Apr 21, 2017 at 1:08 PM, Florian Bertholin <notifications@github.com

**Comment by arkan** [comment]
Hey, thanks for the reply! 

Here is what I have if I run a `-v` on the SSH command: 

```
$> ssh -v -p 8081 127.0.0.1
OpenSSH_7.4p1, LibreSSL 2.5.0
debug1: Reading configuration data /Users/arkan/.ssh/config
debug1: /Users/arkan/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to 127.0.0.1 [127.0.0.1] port 8081.
debug1: Connection established.
debug1: identity file /Users/arkan/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/arkan/.ssh/id_rsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4
```

And then the connection is blocked. If you need anything else let me know.

**Comment by soheilhy** [comment]
I think this is a cmux bug. Can you please try branch fix-44 to see if it fixes your issue and doesn't cause any other regressions for you? Thanks!
https://github.com/soheilhy/cmux/tree/fix-44

**Comment by arkan** [comment]
Hey, I tried it out on my project and it seems to be working as expected :) 
Thanks for the patch.

**Comment by soheilhy** [comment]
Thanks for the confirmation.
