### ISSUE TITLE
doc: a typo in README.md

### ISSUE THREAD

**Issue by yaojingguo** [soheilhy/cmux#46]
I think that `s.Register(&ExampleRPCRcvr{})` should be `trpcS.Register(&ExampleRPCRcvr{})` in [README.md](https://github.com/soheilhy/cmux/blob/master/README.md).

**Comment by puellanivis** [comment]
This correction looks correct to me as well.

**Comment by soheilhy** [comment]
Yes, indeed. That was a typo introduced last time, I changed the README file. Care to send me a pull-request?
