### ISSUE TITLE
Matching a no-op tcp connection will blocking for-ever

### ISSUE THREAD

**Issue by barryz** [soheilhy/cmux#65]
Once a tcp connection established, but without send any data. Like `nc localhost 8080` with no latter
operations.

This may cause the matching process to block for-ever until a min length of data is received and the connection may never receives a stop signal(`donec`).  Issue code line : https://github.com/soheilhy/cmux/blob/8a8ea3c53959009183d7914522833c1ed8835020/cmux.go#L184

**Comment by july2993** [comment]
maybe you can set `SetReadTimeout`  to address you problem

**Comment by barryz** [comment]
yep, I already fix it. Thanks for your reply.

Jiahao Huang <notifications@github.com> 于2019年1月24日周四 下午8:16写道：
